"""add shiprocket fields and product weight

Revision ID: b48804850a04
Revises: 
Create Date: 2026-07-03 18:19:02.634045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48804850a04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shiprocket_order_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shiprocket_shipment_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('awb_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('courier_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('courier_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tracking_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('weight')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('tracking_url')
        batch_op.drop_column('courier_rate')
        batch_op.drop_column('courier_name')
        batch_op.drop_column('awb_number')
        batch_op.drop_column('shiprocket_shipment_id')
        batch_op.drop_column('shiprocket_order_id')

    # ### end Alembic commands ###
